{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "universal.name" . }}
  labels:
    {{- include "universal.labels" . | nindent 4 }}
{{- end }}
